version: 0.2

phases:
  install:
    commands:
      - echo "Using pre-installed PHP and Composer"
      - apt-get update -y  # Keep this to update the system, but not PHP

  build:
    commands:
      - echo "Building Magento"
      - composer install --no-dev --ignore-platform-req=ext-sodium
      - chmod -R 777 var/ generated/
      - php bin/magento setup:upgrade
      - php bin/magento setup:di:compile
      - php bin/magento setup:static-content:deploy -f  # Added -f to force deploy even if no changes

  post_build:
    commands:
      - echo "Build Completed"
