version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3  # Use PHP 8.3 for Magento 2.4.7-p2
    commands:
    
      - sudo apt-get update
      - echo Installing Composer...
      - echo Installing Magento dependencies...

  build:
    commands:
      - echo Building Magento application...
      - php bin/magento setup:upgrade
      - php bin/magento deploy:mode:set production
      - php bin/magento cache:flush

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: 'pub'
