version: 0.2

phases:
  install:
    commands:
      - echo "Using pre-installed PHP and Composer"
      - apt-get update -y  # Keep this to update the system, but not PHP
      - apt-get install -y git unzip curl  # Only install other dependencies if needed

  build:
    commands:
      - echo "Building Magento"
      - composer install --no-dev  # This will use the pre-installed Composer
      - chmod -R 777 var/ generated/
      - php bin/magento setup:upgrade
      - php bin/magento setup:di:compile
      - php bin/magento setup:static-content:deploy -f  # Added -f to force deploy even if no changes

  post_build:
    commands:
      - echo "Build Completed"
