version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing dependencies...
      - sudo apt update
  build:
    commands:
      - echo Build started
      - echo Building Magento
      - php bin/magento setup:upgrade
      - php bin/magento deploy:mode:set production
      - php bin/magento cache:flush
artifacts:
  files:
    - '**/*'
  base-directory: 'pub'
