version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      # Skip Composer installation since it's already installed
      - echo Using existing Composer installation...
      - echo Installing Magento dependencies...
      - composer install

  build:
    commands:
      - echo Building Magento application...
      - php bin/magento setup:upgrade
      - php bin/magento deploy:mode:set production
      - php bin/magento cache:flush

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: 'pub'
