version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3  # Use PHP 8.3 for Magento 2.4.7-p2
    commands:
      # Install PHP dependencies and tools
      - echo Installing PHP dependencies...
      - sudo apt-get update
      - sudo apt-get install -y php-pear php8.3-dev

      # Install Sodium extension via PECL
      - echo Installing Sodium extension...
      - sudo pecl install libsodium

      # Enable the Sodium extension
      - echo "extension=sodium.so" | sudo tee -a /etc/php/8.3/cli/php.ini
      - echo "extension=sodium.so" | sudo tee -a /etc/php/8.3/nginx/php.ini

      # Install Magento dependencies
      - echo Installing Composer...
      - echo Installing Magento dependencies...
      - composer install

  build:
    commands:
      - echo Building Magento application...
      - php bin/magento setup:upgrade
      - php bin/magento deploy:mode:set production
      - php bin/magento cache:flush

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  base-directory: 'pub'
